# !/usr/bin/env python

"""
This module will integrate all files generated by filters

0- Crear un directorio
1- Tomar todos los archivos .csv (manualmente, es decir, ya tengo los nombres)
2- Mover esos archivos al nuevo directorio
3- Tomar todos los archivos .jpeg
4- Mover esos archivos al nuevo directorio

A - Crear funcion que genere el nombre del directorio, basada en el nombre del archivo

"""

import sys
import os
import Queue




    ####################################################################
    ###                         pipe in                              ###
    ####################################################################

def pipe_in(dir,file):
    # print("HEY I AM MERGE PIPE  " + file)
    create_dir(dir,file)
    filesQueue = Queue.Queue() #Files queue
    c = 1


    if os.path.isdir(dir):
        # print("This directory exists")
        for file in os.listdir(dir):
            if file == "doc_pat.csv" or file == "ill_inv.csv" or file == "ill_time.csv" or file == "ins_pat.csv" or file == "age_ill.csv" or file == "sex_ill.csv":
                #Move to newDir
                print("HEEEEEYYY")
                c+=1
                print c
            # elif file.endswith(".jpeg"):
                # Move to newDir

    else:
        print("Directory "+ dir +" does not exists")


    ####################################################################
    ###                         pipe out                             ###
    ####################################################################

# def pipe_out(file):



    ####################################################################
    ###                         "main"                               ###
    ####################################################################

# def __main__(file):

# pipe_in("./")


def create_dir(dir,file):
    print("")
    # file = file.replace(".csv", "")
    # new_dir = dir+file+"_Data"
    # os.makedirs(new_dir)

    # print("HEY I AM create_dir")
    # print(dir)
    # print(file)
